Use Northwind;
Go

Select * From INFORMATION_SCHEMA.TABLES;
Select * From INFORMATION_SCHEMA.Views;
Select * From INFORMATION_SCHEMA.PARAMETERS;
Select * From INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;
Select * From INFORMATION_SCHEMA.CHECK_CONSTRAINTS;